test with github summary and master protection

diff --git a/.github/workflows/maven-release.yaml b/.github/workflows/maven-release.yaml
--- a/.github/workflows/maven-release.yaml
+++ b/.github/workflows/maven-release.yaml
@@ -5,6 +5,9 @@ concurrency:
   cancel-in-progress: false
 
 on:
+  push:
+    branches:
+      - "INFRA-8096"
   workflow_dispatch:
 
 permissions:
@@ -23,6 +26,14 @@ jobs:
         uses: actions/checkout@v6
         with:
           fetch-depth: 0
+
+      - name: Ensure Release Runs On Master Only
+        run: |
+          if [ "${{ github.ref_name }}" != "master" ]; then
+            echo "ERROR: Maven releases must be triggered from the 'master' branch."
+            echo "Current branch is '${{ github.ref_name }}'."
+            exit 1
+          fi
 
       - name: Configure Git User
         run: |
@@ -77,8 +88,17 @@ jobs:
         env:
           MAVEN_GPG_PASSPHRASE: ${{ secrets.SONATYPE_GPG_PASSPHRASE }}
 
-      - name: Push Changes & Tags
+#      - name: Push Changes & Tags
+#        if: success()
+#        run: |
+#          git push origin master
+#          git push origin --tags
+
+      - name: Generate Release Summary
         if: success()
         run: |
-          git push origin master
-          git push origin --tags
+          echo "### Maven Release successfully staged!" >> $GITHUB_STEP_SUMMARY
+          echo "The artifacts for \`${{ github.ref_name }}\` have been signed and uploaded." >> $GITHUB_STEP_SUMMARY
+          echo "" >> $GITHUB_STEP_SUMMARY
+          echo "**Next Step:** You need to manually drop or approve the staging bundle." >> $GITHUB_STEP_SUMMARY
+          echo "Click here to validate your release: [Sonatype Central Portals](https://central.sonatype.com/publishing)" >> $GITHUB_STEP_SUMMARY
